apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-qa-east
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/ali-hamza-noor/deployments.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://k3d-qa-east-serverlb:6443
    namespace: guestbook
  syncPolicy:
    syncOptions:
      - CreateNamespace=true