apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - cluster: dev
            url: https://k3d-dev-serverlb:6443
          - cluster: tst
            url: https://k3d-tst-serverlb:6443
          - cluster: qa
            url: https://k3d-qa-serverlb:6443
          - cluster: dev-west
            url: https://k3d-dev-west-serverlb:6443
          - cluster: qa-east
            url: https://k3d-qa-east-serverlb:6443
          - cluster: tst-west
            url: https://k3d-tst-west-serverlb:6443
  template:
    metadata:
      name: '{{.cluster}}-guestbook'
    spec:
      project: my-project
      source:
        repoURL: https://github.com/ali-hamza-noor/deployments.git
        targetRevision: HEAD
        path: guestbook/{{.cluster}}
      destination:
        server: '{{.url}}'
        namespace: guestbook