apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook-qa-east-19
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/ali-hamza-noor/deployments.git
    targetRevision: HEAD
    path: guestbook
  destination:
    server: https://k3d-qa-east-serverlb:6443
    namespace: guestbook
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
